version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - "db"

  db:
    image:  keinos/sqlite3:latest
    volumes:
      - ./product_last_my_first.db:/product_last_my_first.db

